# Generated by Django 5.2.17 on 2026-08-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial_multi_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='True after the user confirms their email address.'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_locked',
            field=models.BooleanField(default=False, help_text='When True, registration details cannot be changed by the user.'),
        ),
    ]
