import { useEffect, useState } from 'react'
import { listAdminRequests, updateAdminRequest, type AdminRequest } from '../api/adminRequests'
import SiteHeader from '../components/SiteHeader'
import { getErrorMessage } from '../utils/errors'

export default function AdminRequestsPage() {
  const [items, setItems] = useState<AdminRequest[]>([]); const [count, setCount] = useState(0); const [page, setPage] = useState(1)
  const [status, setStatus] = useState('open'); const [kind, setKind] = useState(''); const [error, setError] = useState(''); const [selected, setSelected] = useState<AdminRequest | null>(null); const [reply, setReply] = useState('')
  const load = async () => { try { const data = await listAdminRequests({ page, status, kind }); setItems(data.results); setCount(data.count) } catch (err) { setError(getErrorMessage(err, 'Could not load user requests.')) } }
  useEffect(() => { load() }, [page, status, kind])
  const save = async (resolved?: boolean) => { if (!selected) return; try { await updateAdminRequest(selected.id, { reply, ...(resolved !== undefined ? { resolved } : {}) }); setSelected(null); await load() } catch (err) { setError(getErrorMessage(err, 'Could not update this request.')) } }
  return <div className="page-shell"><SiteHeader /><div className="dash-shell wide"><header className="dash-header compact"><div><p className="brand light">Administration</p><h1>User Requests</h1><p className="header-sub">Requests and feedback from students and teachers, newest first.</p></div></header>{error && <p className="error">{error}</p>}<section className="dash-panel"><div className="user-export-controls"><label>Status<select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}><option value="open">Open</option><option value="resolved">Resolved</option><option value="">All</option></select></label><label>Type<select value={kind} onChange={(e) => { setKind(e.target.value); setPage(1) }}><option value="">All types</option><option value="REQUEST">Request</option><option value="FEEDBACK">Feedback / suggestion</option></select></label></div><p className="header-sub">{count} request{count === 1 ? '' : 's'}</p><div className="table-wrap"><table><thead><tr><th>Date / time</th><th>From</th><th>Type</th><th>Subject</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.user.first_name || item.user.username}<br /><span className="muted">{item.user.email}</span></td><td>{item.kind === 'REQUEST' ? 'Request' : 'Feedback'}</td><td>{item.subject}</td><td>{item.resolved ? 'Resolved' : 'Open'}</td><td><button type="button" className="home-btn" onClick={() => { setSelected(item); setReply(item.reply) }}>View / reply</button></td></tr>)}{items.length === 0 && <tr><td colSpan={6}>No requests found.</td></tr>}</tbody></table></div><div className="form-actions"><button type="button" className="tab" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button type="button" className="tab" disabled={items.length === 0 || page * 20 >= count} onClick={() => setPage(page + 1)}>Next</button></div></section>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)} role="presentation"><div className="dash-panel edit-user-modal" role="dialog" aria-modal="true" onClick={(e) => e.stopPropagation()}><h2>{selected.subject}</h2><p className="header-sub">{selected.user.first_name || selected.user.username} · {new Date(selected.created_at).toLocaleString()}</p><p>{selected.message}</p><label>Reply<textarea rows={5} value={reply} onChange={(e) => setReply(e.target.value)} /></label><div className="form-actions"><button type="button" className="tab" onClick={() => setSelected(null)}>Cancel</button><button type="button" onClick={() => save()}>Save reply</button><button type="button" onClick={() => save(!selected.resolved)}>{selected.resolved ? 'Reopen' : 'Mark resolved'}</button></div></div></div>}</div></div>
}
