import { useEffect, useState, type FormEvent } from 'react'
import { listMyAdminRequests, listMyTeacherRequests, sendAdminRequest, sendTeacherRequest, type AdminRequest, type TeacherRequest } from '../api/adminRequests'
import { listClasses } from '../api/classes'
import SiteHeader from '../components/SiteHeader'
import { useAuth } from '../auth/AuthContext'
import { getErrorMessage } from '../utils/errors'
import type { TeachingClassListItem } from '../types/classes'

export default function CommunicationsPage({ target }: { target: 'admin' | 'teacher' }) {
  const { user } = useAuth(); const [kind, setKind] = useState<'REQUEST' | 'FEEDBACK'>('REQUEST'); const [subject, setSubject] = useState(''); const [message, setMessage] = useState(''); const [classId, setClassId] = useState(''); const [classes, setClasses] = useState<TeachingClassListItem[]>([]); const [items, setItems] = useState<(AdminRequest | TeacherRequest)[]>([]); const [error, setError] = useState(''); const [success, setSuccess] = useState('')
  const load = async () => { try { setItems(target === 'admin' ? await listMyAdminRequests() : await listMyTeacherRequests()); if (target === 'teacher') setClasses(await listClasses()) } catch (err) { setError(getErrorMessage(err, 'Could not load messages.')) } }
  useEffect(() => { load() }, [target])
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); try { const item = target === 'admin' ? await sendAdminRequest({ kind, subject, message }) : await sendTeacherRequest({ class_id: Number(classId), kind, subject, message }); setItems((old) => [item, ...old]); setSubject(''); setMessage(''); setSuccess('Your message has been sent.') } catch (err) { setError(getErrorMessage(err, 'Could not send your message.')) } }
  if (!user) return null
  const title = target === 'admin' ? 'Communicate with the admin team' : 'Communicate with your teacher'
  return <div className="page-shell"><SiteHeader /><div className="dash-shell"><header className="dash-header compact"><div><p className="brand light">Communication</p><h1>{title}</h1></div></header><section className="dash-panel">{error && <p className="error">{error}</p>}{success && <p className="success">{success}</p>}<form className="admin-form" onSubmit={submit}><div className="form-grid">{target === 'teacher' && <label>Class<select value={classId} onChange={(e) => setClassId(e.target.value)} required><option value="">Select a class…</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<label>Message type<select value={kind} onChange={(e) => setKind(e.target.value as 'REQUEST' | 'FEEDBACK')}><option value="REQUEST">Request</option><option value="FEEDBACK">Feedback / suggestion</option></select></label><label className={target === 'teacher' ? '' : 'full'}>Subject<input value={subject} onChange={(e) => setSubject(e.target.value)} required maxLength={200} /></label><label className="full">Message<textarea value={message} onChange={(e) => setMessage(e.target.value)} rows={5} required /></label></div><button className="home-btn">Send message</button></form><div className="my-admin-requests"><h2>Your recent messages</h2>{items.map((item) => <article key={item.id}><strong>{item.subject}</strong><span className="muted"> · {'class_name' in item ? `${item.class_name} · ` : ''}{new Date(item.created_at).toLocaleString()} · {item.resolved ? 'Resolved' : 'Open'}</span><p>{item.message}</p>{item.reply && <p className="admin-reply"><strong>Reply:</strong> {item.reply}</p>}</article>)}{items.length === 0 && <p className="header-sub">No messages yet.</p>}</div></section></div></div>
}
