import { useEffect, useState } from 'react'
import { listTeacherRequests, updateTeacherRequest, type TeacherRequest } from '../api/adminRequests'
import SiteHeader from '../components/SiteHeader'
import { getErrorMessage } from '../utils/errors'

export default function TeacherRequestsPage() {
  const [items, setItems] = useState<TeacherRequest[]>([]); const [count, setCount] = useState(0); const [page, setPage] = useState(1); const [status, setStatus] = useState('open'); const [selected, setSelected] = useState<TeacherRequest | null>(null); const [reply, setReply] = useState(''); const [error, setError] = useState('')
  const load = async () => { try { const data = await listTeacherRequests(page, status); setItems(data.results); setCount(data.count) } catch (err) { setError(getErrorMessage(err, 'Could not load student requests.')) } }
  useEffect(() => { load() }, [page, status])
  const save = async (resolved?: boolean) => { if (!selected) return; try { await updateTeacherRequest(selected.id, { reply, ...(resolved === undefined ? {} : { resolved }) }); setSelected(null); await load() } catch (err) { setError(getErrorMessage(err, 'Could not update the request.')) } }
  return <div className="page-shell"><SiteHeader /><div className="dash-shell wide"><header className="dash-header compact"><div><p className="brand light">Teaching</p><h1>Student Requests</h1><p className="header-sub">Student messages, newest first.</p></div></header>{error && <p className="error">{error}</p>}<section className="dash-panel"><label>Status<select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1) }}><option value="open">Open</option><option value="resolved">Resolved</option><option value="">All</option></select></label><p className="header-sub">{count} request{count === 1 ? '' : 's'}</p><div className="table-wrap"><table><thead><tr><th>Date / time</th><th>Student email</th><th>Class</th><th>Type</th><th>Subject</th><th>Status</th><th></th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{new Date(item.created_at).toLocaleString()}</td><td>{item.student.email}</td><td>{item.class_name}</td><td>{item.kind === 'REQUEST' ? 'Request' : 'Feedback'}</td><td>{item.subject}</td><td>{item.resolved ? 'Resolved' : 'Open'}</td><td><button type="button" className="home-btn" onClick={() => { setSelected(item); setReply(item.reply) }}>View / reply</button></td></tr>)}{!items.length && <tr><td colSpan={7}>No requests found.</td></tr>}</tbody></table></div><div className="form-actions"><button type="button" className="tab" disabled={page === 1} onClick={() => setPage(page - 1)}>Previous</button><span>Page {page}</span><button type="button" className="tab" disabled={!items.length || page * 20 >= count} onClick={() => setPage(page + 1)}>Next</button></div></section>{selected && <div className="modal-backdrop" role="presentation" onClick={() => setSelected(null)}><div className="dash-panel edit-user-modal" role="dialog" aria-modal="true" onClick={(event) => event.stopPropagation()}><h2>{selected.subject}</h2><p className="header-sub">{selected.student.email} · {selected.class_name}</p><p>{selected.message}</p><label>Reply<textarea rows={5} value={reply} onChange={(e) => setReply(e.target.value)} /></label><div className="form-actions"><button type="button" className="tab" onClick={() => setSelected(null)}>Cancel</button><button type="button" onClick={() => save()}>Save reply</button><button type="button" onClick={() => save(!selected.resolved)}>{selected.resolved ? 'Reopen' : 'Mark resolved'}</button></div></div></div>}</div></div>
}
