# Generated by Django 5.2.8 on 2026-09-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_normalize_school_slugs_to_dns_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='subtype',
        ),
        migrations.DeleteModel(
            name='SchoolSubtype',
        ),
        migrations.DeleteModel(
            name='SchoolType',
        ),
    ]
