# Generated by Django 6.0.3 on 2026-09-25 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_alter_academiccalendarentry_entry_type_academicterm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicterm',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='academiccalendarentry',
            name='entry_type',
            field=models.CharField(choices=[('WEEK', 'Teaching week'), ('EXAM_WEEK', 'Exam week'), ('HOLIDAY', 'Holiday')], max_length=12),
        ),
    ]
