# Generated by Django 6.0.3 on 2026-09-25 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_academicterm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendarentry',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendarentry',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
