# Generated by Django 6.0.3 on 2026-09-25 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_academiccalendarentry_end_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccalendarentry',
            options={'ordering': ['display_order', 'start_date', 'title', 'id']},
        ),
    ]
